version: "3.8"

services:
  web:
    build: ./web
    container_name: flask_app
    ports:
      - "80:80"
    volumes:
      - ./web:/app
    networks:
      sap_network:
        ipv4_address: 172.20.0.2

  database:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: flask_app
    volumes:
      - mysql-storage:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      sap_network:
        ipv4_address: 172.20.0.3

  grafana:
    image: grafana/grafana:latest
    container_name: grafana_app
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - grafana-conf:/etc/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin # Vous pouvez changer cela pour une meilleure sécurité
      - GF_SECURITY_ALLOW_EMBEDDING=true
    networks:
      sap_network:
        ipv4_address: 172.20.0.4

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_app
    ports:
      - "9090:9090"
    volumes:
      - prometheus-data:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      sap_network:
        ipv4_address: 172.20.0.5

volumes:
  grafana-conf:
  grafana-data:
  mysql-storage:
  prometheus-data:

networks:
  sap_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1
